language: node_js
node_js:
- 8
- 7
- 6
deploy:
  provider: npm
  email: petrusxz@gmail.com
  api_key:
    secure: tI/CmQWRA9JFfWPrqngfG0VAmdd190Q/t3Nkr9LXyS0b3auqbZ+dn6yUuW9mCUuFAJzS9jJ5cd3uzLLhIIT9bpW9RDEz8iddGwsUY6VAsoSIDH7+/zRKcYQnZ3TZdAlG8H2XIBO9eCl2xA4RQasYgHtyiIfw5OKgWX8tpL5+jpJBWxO1KuaFavrCqdFjrw5tNDdSEzukgNa6FFvhCmmO25kmEiIq/rO4e82DnGpwLg0RQiM0Od3TnmZ/1EHonPjC22fyka+aiEZEFATClxinEZ5zfUCIlnXSiK9JfoZyyg9Pbna6xJOWThsfnUZR1uWMpnU2l42La0WNIeR28ED3xs9TdxysJjp+3bSTFXwFYePHig+VGF2UDaogWm9K4I6yqAQYD7gA1sgGRA9v7HWmhPiC76xSh89mmcUKaJmhfhAyGGX43rtWcMEEqVMrMbgcdion7lfw5P3YW7rwWUFYxgPMQEzUPDUyGS+/Q+LF4EEizP2aUlbVtVaz7vKkyiQAAQQXELvyWSm0hH+z6Lb+XpqmjSVkh15PtYp6Dq2zJH3o0alhsqd/BLsf3w4kA4Jpadrdlamiv9p1X8Ln6N8RvspmRFGSQnp6GRQ/i7Q0Y+fmyUogz/1N9oWf+JAoLMJBiqS4sEoVmW5l+eA4RDn4Ecb7FyGuFAMAFagYWbPZsh0=
